### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by djfarrelly** [bufferapp/micro-rpc#1]
Can we update the docs for this repo on how to configure for an express server? It seems everything it still written for micro :)

PS - Should we rename this library since it's not depending on micro under the hood anymore? 🤔

**Comment by hharnisc** [comment]
So long as express doesn't handle async/await we'll have the handler function with a catch: https://github.com/bufferapp/buffer-publish/blob/master/packages/server/index.js#L85-L98

I rewrote the `express` version here: https://github.com/bufferapp/buffer-rpc

So we should just be able to deprecate this after we swap it out.
